### PR TITLE
deps: Update Prisma to 4.3.1 & Reflector to 0.15.3

### PR DESCRIPTION
**Pull request by tatianainama**
closes CP-2635

### CODE REVIEW

**Comment by tatianainama** [comment]
@prisma/devprod-eng I'm am not able to update snapshots locally, I've run into this before getting the following error:

```
 FAIL  tests/templates-static-data.spec.ts
  ● Test suite failed to run


      x Expected unicode escape
          ,-[/Users/tati/git/templates/src/generated/templates/Nextjs.ts:4790:15]
     4790 | const errMessage = \`Chalk template literal is missing \${styles.length} closing bracket\${styles.length === 1 ? "" : "s"} (\\`}\\`)\`;
          :                                                                                                                                  ^
          `----


    Caused by:
        0: failed to process input file
        1: Syntax Error
```

Does anyone have an idea on how to fix this?

**Comment by jasonkuhrt** [comment]
Hm, pulled down locally and it works so far:

CleanShot 2022-09-06 at 16 20 11@2x

After new build I get other expected errors:

CleanShot 2022-09-06 at 16 21 31@2x


@tatianainama super weird that you're seeing _that_ error. I looked at my local file and it only has 1117 lines yet your error message has 4790 shown. Can you confirm what your file actually has?

**Comment by jasonkuhrt** [comment]
Meanwhile have updated snaps to help unblock things this time around.

**Comment by tatianainama** [comment]
> @tatianainama super weird that you're seeing that error. I looked at my local file and it only has 1117 lines yet your error message has 4790 shown. Can you confirm what your file actually has?

I checked and the file size is 500MB 😰 (took me a minute to be able to opened it)

I cleaned up the generated folder, ran `build:gen` again and got heap out of memory errors 

<details>

<summary> Long Stacktrace </summary>

```
1 ● generateTypeScript Found templates:  --  templates: [ 'Blog', 'Empty', 'Music Streaming Service', 'Rentals Platform', 'SaaS', 'URL Shortener' ]

<--- Last few GCs --->

[13184:0x130008000]    38931 ms: Mark-sweep 3348.3 (3386.8) -> 3348.1 (3386.8) MB, 11.5 / 0.0 ms  (average mu = 0.972, current mu = 0.959) allocation failure scavenge might not succeed
[13184:0x130008000]    39070 ms: Mark-sweep 4312.4 (4335.4) -> 4312.4 (4350.9) MB, 40.8 / 0.0 ms  (average mu = 0.907, current mu = 0.706) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100c198d8 node::Abort() [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
 2: 0x100c19a60 node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
 3: 0x100d5b36c v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
 4: 0x100d5b300 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
 5: 0x100ede81c v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
 6: 0x100edd33c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
 7: 0x100ee8684 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
 8: 0x100ee8718 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
 9: 0x100ebb5ac v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
10: 0x1011f36d0 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
11: 0x101506b8c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
12: 0x101508420 Builtins_SubString [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
13: 0x10155cd78 Builtins_RegExpReplace [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
14: 0x1014fa9f0 Builtins_StringPrototypeReplace [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
15: 0x1060aa550 
16: 0x1060a8c90 
17: 0x10149a818 Builtins_InterpreterEntryTrampoline [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
18: 0x10149a818 Builtins_InterpreterEntryTrampoline [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
19: 0x101522fe8 Builtins_ArrayMap [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
20: 0x10149a818 Builtins_InterpreterEntryTrampoline [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
21: 0x1014c9e14 Builtins_AsyncFunctionAwaitResolveClosure [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
22: 0x10154ec78 Builtins_PromiseFulfillReactionJob [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
23: 0x1014bc1f4 Builtins_RunMicrotasks [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
24: 0x1014984e4 Builtins_JSRunMicrotasksEntry [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
25: 0x100e6afcc v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
26: 0x100e6b400 v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
27: 0x100e6b4ec v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
28: 0x100e8e128 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
29: 0x100e8e9bc v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
30: 0x100b69c4c node::InternalCallbackScope::Close() [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
31: 0x100b69fc8 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
32: 0x100b7e8f0 node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
33: 0x100c1dd50 node::fs::FSReqCallback::Resolve(v8::Local<v8::Value>) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
34: 0x100c1e448 node::fs::AfterNoArgs(uv_fs_s*) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
35: 0x101478bc0 uv__work_done [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
36: 0x10147c35c uv__async_io [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
37: 0x10148e0a8 uv__io_poll [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
38: 0x10147c7ec uv_run [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
39: 0x100b6a6d4 node::SpinEventLoop(node::Environment*) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
40: 0x100c51328 node::NodeMainInstance::Run(int*, node::Environment*) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
41: 0x100c51008 node::NodeMainInstance::Run() [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
42: 0x100beda40 node::Start(int, char**) [/Users/tati/Library/pnpm/nodejs/16.17.0/bin/node]
43: 0x1056f908c 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

I increased the heap mem limit to 8GB and the `build:gen` command worked, but ended up again with a 500MB generated file with corrupted content

**Comment by tatianainama** [comment]
> Meanwhile have updated snaps to help unblock things this time around.

Thank you so much 🙏 
Just one thing, this one is also missing an update `tests/__snapshots__/templates-instances.spec.ts.snap` 🙈

**Pull request merged**
